apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
data:
  run.sh: |
{{ tpl (.Files.Get "scripts/run.sh") . | indent 4 }}
{{- if .Values.bidpricescript }}
  price_script.sh: |
{{ .Values.bidpricescript | b64dec | indent 4 }}
{{- end }}
