apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider.fullname" . }}-keys
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  key.txt: {{ .Values.provider.key | quote }}
  key-pass.txt: {{ .Values.provider.keySecret | quote }}
