# Default values for provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: spheronnetwork/devnet-provider
  pullPolicy: Always
  tag: latest-amd64

from:
key:
keysecret:
chainid: spheronnet-2
domain:
home: "/root/.spheron"
node: "https://spheron-rpc.polkachu.com:443"
keyringbackend: "test"

# Your provider contact details we submit to the chain
email:
website:

# Important to know about the gas and fees:
#
# fees = (gas * gas-prices) as per Cosmos SDK docs.
# (200000 * 0.025uakt) = 5000uakt floor fee for most of RPC nodes.
#
# Akash RPC nodes set --minimum-gas-prices=0.025uakt which gives
# 5000uakt minimum fee when multiplied by the gas price (200000 default).
#
# Akash clients should respect this and set --gas-prices to 0.025uakt
#
# Note that RPC node running without minimum-gas-prices set will accept
# 0uakt fee transactions which is not desirable as per Cosmos SDK docs.
#
# --gas argument works only when --gas-prices is set!
# Note that the clients cannot provide both fees and gas prices!
#
# Anything you set here will get globally exposed via AKASH_GAS_PRICES,
# AKASH_GAS, AKASH_GAS_ADJUSTMENT environment variables in
# charts/spheron-provider/templates/deployment.yaml
gasprices: "0.025uakt"
# set --gas to 200000 (or higher) to meet Akash RPC's minimum fees, (--minimum-gas-prices X 200000) = 5000uakt.
# or set --gas to "auto" to leverage the gasadjustment setting;
# increase gasadjustment to tackle "out of gas" issues, i.e. https://github.com/ovrclk/spheron/issues/1508
gas: "auto"
# Note that --gas-adjustment is working only when --gas is "auto"!
gasadjustment: "1.5"

bidmindeposit: "500000uakt" # 0.5 AKT - provider minimum bid deposit (5 AKT for sandbox)

# If you plan to use bid price script, then make sure to set bidpricescript variable to the base64 encoded contents of the script.
# This will automatically switch AKASH_BID_PRICE_STRATEGY from "scale" (default) to "shellScript".
# Sample scripts can be found under charts/spheron-provider/scripts/ directory.
# Example usage:
# --set bidpricescript="$(cat ./charts/spheron-provider/scripts/price_script_generic.sh | openssl base64 -A)"
bidpricecpuscale: "0.004"
bidpricememoryscale: "0.0016"
bidpriceendpointscale: "1"
# set pricing for leased IP
# 1 IP would cost ((1*60*429903)/10^6)*0.194 = $5/month (if 1 AKT = $0.194; and 429903 blocks a month)
bidpriceipscale: "60"
# set storage pricing for your StorageClass you are using
# here is an example for beta2 StorageClass:
bidpricestoragescale: "0.00016,beta2=0.00016"
withdrawalperiod: "1h"
minimumbalance: "10000000"
bidpricestrategy: "randomRange"
deploymentnetworkpoliciesenabled: "false"
cluster_node_port_quantity: "2500"

ipoperator: false

debug: "false"

# Percentage of CPU overcommit
overcommit_pct_cpu: 0
# Percentage of memory overcommit
overcommit_pct_mem: 0
# Percentage of storage overcommit
overcommit_pct_storage: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
