# Default values for inventory-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: spheronnetwork/unstable-devnet-provider
  pullPolicy: Always
  tag: latest-amd64

inventoryConfig:
  # Allow users to specify cluster storage options
  cluster_storage:
    - default
    - beta3
    - ram
  exclude:
    nodes: []
    node_storage: []

config:
  url: https://spheron-release.s3.amazonaws.com/static/gpus.json
