apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    spheron.network: "true"
    app.kubernetes.io/name: spheron
    app.kubernetes.io/instance: gateway
    app.kubernetes.io/component: provider
    {{- include "provider.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.apiport }}
      targetPort: api
    - name: ws
      protocol: TCP
      port: {{ .Values.wsport }}
      targetPort: ws
    - name: tunnel
      protocol: TCP
      port: {{ .Values.tunnelport }}
      targetPort: tunnel
  
  selector:
    app: {{ include "provider.fullname" . }}
    {{- include "provider.selectorLabels" . | nindent 4 }}
