---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spheron-operator-hostname
  labels:
    app.kubernetes.io/name: hostname
    app.kubernetes.io/instance: hostname-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
subjects:
  - kind: ServiceAccount
    name: operator-hostname
    namespace: spheron-services
roleRef:
  kind: ClusterRole
  name: spheron-operator-hostname
  apiGroup: rbac.authorization.k8s.io