---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory
  namespace: spheron-services
  labels:
    spheron.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory-hardware-discovery
  namespace: spheron-services
  labels:
    spheron.network: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-hardware-discovery
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider